/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Convex_hull_3;

import CGAL.Kernel.Point_3;
import CGAL.Kernel.Plane_3;
import CGAL.Polyhedron_3.Polyhedron_3;
import java.util.Iterator;

public class CGAL_Convex_hull_3 {
  public static void convex_hull_3(Iterator<Point_3> range, Polyhedron_3 P) {
    CGAL_Convex_hull_3JNI.convex_hull_3(range, Polyhedron_3.getCPtr(P), P);
  }

  public static void halfspace_intersection_3(Iterator<Plane_3> range, Polyhedron_3 P) {
    CGAL_Convex_hull_3JNI.halfspace_intersection_3__SWIG_0(range, Polyhedron_3.getCPtr(P), P);
  }

  public static void halfspace_intersection_3(Iterator<Plane_3> range, Polyhedron_3 P, Point_3 pt) {
    CGAL_Convex_hull_3JNI.halfspace_intersection_3__SWIG_1(range, Polyhedron_3.getCPtr(P), P, Point_3.getCPtr(pt), pt);
  }

  public static boolean is_strongly_convex_3(Polyhedron_3 P) {
    return CGAL_Convex_hull_3JNI.is_strongly_convex_3(Polyhedron_3.getCPtr(P), P);
  }

}
