/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Convex_hull_3;

import CGAL.Kernel.Point_3;
import CGAL.Kernel.Plane_3;
import CGAL.Polyhedron_3.Polyhedron_3;
import java.util.Iterator;

public class CGAL_Convex_hull_3JNI {

    static {
      try {
          System.loadLibrary("CGAL_Convex_hull_3");
      } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library CGAL_Convex_hull_3 failed to load. \n" + e);
        throw e;
      }
    }
  

    static{
      try {
          System.loadLibrary("CGAL_Java");
      } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library CGAL_Java failed to load. \n" + e);
        throw e;
      }
    }
  
  public final static native void convex_hull_3(Iterator<Point_3> jarg1, long jarg2, Polyhedron_3 jarg2_);
  public final static native void halfspace_intersection_3__SWIG_0(Iterator<Plane_3> jarg1, long jarg2, Polyhedron_3 jarg2_);
  public final static native void halfspace_intersection_3__SWIG_1(Iterator<Plane_3> jarg1, long jarg2, Polyhedron_3 jarg2_, long jarg3, Point_3 jarg3_);
  public final static native boolean is_strongly_convex_3(long jarg1, Polyhedron_3 jarg1_);
}
