/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polygon_mesh_processing;

import java.util.Iterator;
import java.util.Collection;
import CGAL.Polyhedron_3.Polyhedron_3;
import CGAL.Polyhedron_3.Polyhedron_3_Facet_handle;
import CGAL.Polyhedron_3.Polyhedron_3_Vertex_handle;
import CGAL.Polyhedron_3.Polyhedron_3_Halfedge_handle;
import CGAL.Kernel.Point_3;
import CGAL.Kernel.Vector_3;
import CGAL.Kernel.Bbox_3;

public interface CGAL_Polygon_mesh_processingConstants {
  public final static double CGAL_VERSION = 4.11;
  public final static int CGAL_VERSION_NR = 1041101000;
  public final static int CGAL_SVN_REVISION = 99999;
  public final static int CGAL_RELEASE_DATE = 20170920;
  public final static String CGAL_VERSION_STR = "4.11";
}
