/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polyline_simplification_2;

public class Hybrid_squared_distance_cost {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Hybrid_squared_distance_cost(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Hybrid_squared_distance_cost obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polyline_simplification_2JNI.delete_Hybrid_squared_distance_cost(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Hybrid_squared_distance_cost(double ratio) {
    this(CGAL_Polyline_simplification_2JNI.new_Hybrid_squared_distance_cost(ratio), true);
  }

}
