/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polyline_simplification_2;
import CGAL.Java.JavaData; import CGAL.Kernel.Point_2;
public class PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polyline_simplification_2JNI.delete_PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle() {
    this(CGAL_Polyline_simplification_2JNI.new_PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle(), true);
  }

  public Point_2 point() {
    return new Point_2(CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_point__SWIG_0(swigCPtr, this), true);
  }

  public void point(Point_2 ref) {
    CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_point__SWIG_1(swigCPtr, this, Point_2.getCPtr(ref), ref);
  }

  public void set_point(Point_2 c) {
    CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_set_point(swigCPtr, this, Point_2.getCPtr(c), c);
  }

  public boolean lt(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle p) {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_lt(swigCPtr, this, PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle.getCPtr(p), p);
  }

  public boolean gt(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle p) {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_gt(swigCPtr, this, PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle.getCPtr(p), p);
  }

  public boolean le(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle p) {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_le(swigCPtr, this, PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle.getCPtr(p), p);
  }

  public boolean ge(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle p) {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_ge(swigCPtr, this, PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle.getCPtr(p), p);
  }

  public boolean equals(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle p) {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_equals(swigCPtr, this, PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle.getCPtr(p), p);
  }

  public boolean not_equals(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle p) {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_not_equals(swigCPtr, this, PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle.getCPtr(p), p);
  }

  public int hashCode() {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_hashCode(swigCPtr, this);
  }

  public PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle clone() {
    return new PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle(CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle other) {
    CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_clone__SWIG_1(swigCPtr, this, PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle.getCPtr(other), other);
  }

  public boolean is_removable() {
    return CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_is_removable(swigCPtr, this);
  }

  public void set_removable(boolean b) {
    CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_set_removable(swigCPtr, this, b);
  }

  public JavaData info() {
    return new JavaData(CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_info(swigCPtr, this), false);
  }

  public void get_info(JavaData jd) {
    CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_get_info(swigCPtr, this, JavaData.getCPtr(jd), jd);
  }

  public void set_info(JavaData jd) {
    CGAL_Polyline_simplification_2JNI.PS2_Constrained_Delaunay_triangulation_plus_2_Vertex_handle_set_info(swigCPtr, this, JavaData.getCPtr(jd), jd);
  }

}
