/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polyline_simplification_2;

public class Stop_below_count_ratio_threshold {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Stop_below_count_ratio_threshold(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Stop_below_count_ratio_threshold obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polyline_simplification_2JNI.delete_Stop_below_count_ratio_threshold(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Stop_below_count_ratio_threshold(double threshold) {
    this(CGAL_Polyline_simplification_2JNI.new_Stop_below_count_ratio_threshold(threshold), true);
  }

}
