/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polyhedron_3;

public class Polyhedron_3_Modifier_base {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Polyhedron_3_Modifier_base(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Polyhedron_3_Modifier_base obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polyhedron_3JNI.delete_Polyhedron_3_Modifier_base(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Polyhedron_3_Modifier_base() {
    this(CGAL_Polyhedron_3JNI.new_Polyhedron_3_Modifier_base(), true);
  }

}
